services:
  postgresql:
    build:
      context: ./internal/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      mynetwork:
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  goose:
    build:
      dockerfile: ./db/Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
    networks:
      mynetwork:

  matharena:
    build: .
    depends_on:
      - goose
    ports:
      - "8080:8080"
    networks:
      mynetwork:
    environment:
      - TZ=Europe/Moscow
      - DB_CONN_STR=user=postgres dbname=postgres host=postgresql port=5432 sslmode=disable
      - TOKEN_EXPIRATION_TIME=48 # hours
      - TOKEN_SECRET=secret
      - SALT_LENGTH=16

networks:
  mynetwork:
    driver: bridge
