// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	generator "github.com/pelageech/matharena/internal/game/generator"
	math "github.com/pelageech/matharena/internal/game/math"

	mock "github.com/stretchr/testify/mock"
)

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

type Generator_Expecter struct {
	mock *mock.Mock
}

func (_m *Generator) EXPECT() *Generator_Expecter {
	return &Generator_Expecter{mock: &_m.Mock}
}

// Difficulty provides a mock function with given fields:
func (_m *Generator) Difficulty() generator.Difficulty {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Difficulty")
	}

	var r0 generator.Difficulty
	if rf, ok := ret.Get(0).(func() generator.Difficulty); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(generator.Difficulty)
	}

	return r0
}

// Generator_Difficulty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Difficulty'
type Generator_Difficulty_Call struct {
	*mock.Call
}

// Difficulty is a helper method to define mock.On call
func (_e *Generator_Expecter) Difficulty() *Generator_Difficulty_Call {
	return &Generator_Difficulty_Call{Call: _e.mock.On("Difficulty")}
}

func (_c *Generator_Difficulty_Call) Run(run func()) *Generator_Difficulty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Generator_Difficulty_Call) Return(_a0 generator.Difficulty) *Generator_Difficulty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Generator_Difficulty_Call) RunAndReturn(run func() generator.Difficulty) *Generator_Difficulty_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function with given fields:
func (_m *Generator) Generate() math.ExpressionInt {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 math.ExpressionInt
	if rf, ok := ret.Get(0).(func() math.ExpressionInt); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(math.ExpressionInt)
		}
	}

	return r0
}

// Generator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type Generator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *Generator_Expecter) Generate() *Generator_Generate_Call {
	return &Generator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *Generator_Generate_Call) Run(run func()) *Generator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Generator_Generate_Call) Return(_a0 math.ExpressionInt) *Generator_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Generator_Generate_Call) RunAndReturn(run func() math.ExpressionInt) *Generator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewGenerator creates a new instance of Generator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Generator {
	mock := &Generator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
